name: Remote SSH Command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/mythicaldash-v3/frontend/src/locale/
            sudo rm -r translations
            sudo git clone https://github.com/Scale-Hosting-LLC/translations.git
            cd translations
            sudo cp * ../
            sudo systemctl restart nginx
            sudo rm -rf /var/cache/nginx/*
            sudo nginx -s reload
            
