name: Push-to-client

on:
    push:
        branches: [Stable]

jobs:
    build:
        runs-on: ubuntu-latest
        container: ubuntu
        steps:
            - uses: actions/checkout@v2
            - name: Pushes to another repository
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  SSH_DEPLOY_KEY: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                  source-directory: "content"
                  destination-github-username: "Scale-Hosting-LLC"
                  destination-repository-name: "Client-Panel"
                  target-branch: main
                  commit-message: ORIGIN_COMMIT
                  target-directory: "frontend/src/locale"
